spring:
  application:
    name: address-server
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
